### ISSUE TITLE
运行示例应用报错

### ISSUE THREAD

**Issue by YoungZiyi** [mix-go/mix#3]
golang纯小白, 运行示例应用报错

平台
> raspberry pi 2 model b

系统
> Linux ubuntu 5.4.0-1022-raspi #25-Ubuntu SMP PREEMPT Thu Oct 15 14:22:53 UTC 2020 armv7l armv7l armv7l GNU/Linux

报错信息
```
ubuntu@ubuntu:~/projects/hello/bin$ ./go_build_main_go api
time=2020-11-13 08:18:05.454 level=error msg=dial tcp 127.0.0.1:3306: connect: connection refused
goroutine 1 [running]:
runtime/debug.Stack(0x69c658, 0x1288060, 0x6da108)
        /usr/lib/go-1.13/src/runtime/debug/stack.go:24 +0x78
github.com/mix-go/console.(*ErrorHandler).Handle(0x100e9e0, 0x6d43d8, 0x1282050)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/console@v1.0.23/error.go:52 +0x60
github.com/mix-go/console.(*Application).Run.func1(0x12932c0)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/console@v1.0.23/application.go:122 +0xc4
panic(0x6d43d8, 0x1282050)
        /usr/lib/go-1.13/src/runtime/panic.go:679 +0x194
github.com/mix-go/bean.(*BeanDefinition).instance.func1.1(0x1286ae0, 0x12139ac)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/bean@v1.0.22/definition.go:94 +0x16c
panic(0x6d43d8, 0x1282050)
        /usr/lib/go-1.13/src/runtime/panic.go:679 +0x194
github.com/mix-go/bean.(*BeanDefinition).instance.func1(0x1286ae0, 0x12139ac, 0x100d540, 0x2, 0x2)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/bean@v1.0.22/definition.go:102 +0x1b0
github.com/mix-go/bean.(*BeanDefinition).instance(0x1286ae0, 0x6c0750, 0x1213bbc)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/bean@v1.0.22/definition.go:106 +0x2d4
github.com/mix-go/bean.(*ApplicationContext).GetBean(0x12c54c0, 0x774aa5, 0x2, 0x1213c14, 0x1213bec, 0x0, 0x0, 0x75fe58, 0x1010680)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/bean@v1.0.22/context.go:60 +0x118
github.com/mix-go/bean.(*ApplicationContext).Get(...)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/bean@v1.0.22/context.go:69
github.com/mix-go/console.(*Application).Get(...)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/console@v1.0.23/application.go:109
hello/globals.DB(...)
        /home/ubuntu/projects/hello/globals/db.go:9
hello/globals.Init()
        /home/ubuntu/projects/hello/globals/init.go:23 +0x220
hello/listeners.(*CommandListener).Process(0xd32aa0, 0x87eb50, 0x1010710)
        /home/ubuntu/projects/hello/listeners/command.go:24 +0x3c
github.com/mix-go/event.(*ListenerProvider).getListenersForEvent.func1(0x87eb50, 0x1010710)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/event@v1.0.22/provider.go:17 +0x38
github.com/mix-go/event.(*EventDispatcher).Dispatch(0x1010618, 0x87eb50, 0x1010710, 0xe1901, 0x4)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/event@v1.0.22/dispatcher.go:11 +0x80
github.com/mix-go/console.(*Application).call(0x12932c0)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/console@v1.0.23/application.go:202 +0x120
github.com/mix-go/console.(*Application).Run(0x12932c0)
        /home/ubuntu/go/pkg/mod/github.com/mix-go/console@v1.0.23/application.go:161 +0x3b4
main.main()
        /home/ubuntu/projects/hello/main.go:28 +0xac
 file=logger.go:19
```

**Comment by onanying** [comment]
框架的 /home/ubuntu/projects/hello/globals/init.go:23 里面会初始化 redis/db 连接，会使用 .env 环境配置文件里的连接信息，然后 dial tcp 127.0.0.1:3306: connect: connection refused 告诉你了，db连接不上
